[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "triposg"
version = "0.1"
description = "TripoSG package"
readme = "README.md"
requires-python = ">=3.7"

[tool.setuptools]
packages = ["triposg"]
include-package-data = true
